'reinit'
'sdfopen /home/shiv/Documents/GitHub/EES405/datasets/uwnd.jjas.200hpa.nc'
'sdfopen /home/shiv/Documents/GitHub/EES405/datasets/vwnd.jjas.200hpa.nc'
'set gxout shaded'
'd hdivg(uwnd,vwnd.2)'
'set gxout vector and stream'
'd skip(uwnd,2,2);vwnd.2;mag(uwnd,vwnd.2)'
'run cbar'
'draw title Divergence at 200hPa' 
'printim /home/shiv/Documents/GitHub/EES405/datasets/divergence.png'
