'reinit'
'sdfopen /home/shiv/Documents/GitHub/EES405/datasets/mslp.annual.timmean.nc'
'set gxout shaded'
'a = mslp*0.01'
'd a'
'run cbar' 
'draw title ITCZ ANNUAL mslp'
'printim /home/shiv/Documents/GitHub/EES405/datasets/itcz.annual.mslp.png'
'reinit'
'sdfopen /home/shiv/Documents/GitHub/EES405/datasets/mslp.jjas.timmean.nc'
'set gxout shaded'
'a = mslp*0.01'
'd a'
'run cbar' 
'draw title ITCZ JJAS mslp'
'printim /home/shiv/Documents/GitHub/EES405/datasets/itcz.jjas.mslp.png'
'reinit'
'sdfopen /home/shiv/Documents/GitHub/EES405/datasets/mslp.djf.timmean.nc'
'set gxout shaded'
'a = mslp*0.01'
'd a'
'run cbar' 
'draw title ITCZ DJF mslp'
'printim /home/shiv/Documents/GitHub/EES405/datasets/itcz.djf.mslp.png'
