'reinit'
'sdfopen /home/shiv/Documents/GitHub/EES405/datasets/uwnd.jjas.200hpa.nc'
'sdfopen /home/shiv/Documents/GitHub/EES405/datasets/vwnd.jjas.200hpa.nc'
'set gxout shaded'
'd hcurl(uwnd,vwnd.2)'
'set gxout vector and stream'
'd skip(uwnd,1,1);vwnd.2;mag(uwnd,vwnd.2)'
'run cbar'
'draw title Vorticity at 200hPa' 
'printim /home/shiv/Documents/GitHub/EES405/datasets/vorticity.png'
